# Generated by Django 3.2.5 on 2021-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210728_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
